<a href="https://colab.research.google.com/github/meganttp/PLOS-Prediction-Healthcare/blob/main/DAT6000_PLOS_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

# Connect Gogle drive
path = '/content/drive/MyDrive/DATA6000-A1/02Exploratory/Final Cleaning_30-70+Hospital_Inpatient_Discharges_(SPARCS_De-Identified)__2021_20260405).csv'

df = pd.read_csv(path)

print(f"Data Loaded: {df.shape}")
df.head()

Data Loaded: (602176, 15)

,Age Group,Gender,Length of Stay,Type of Admission,Patient Disposition,CCSR Diagnosis Description,CCSR Procedure Description,APR DRG Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Emergency Department Indicator,Total Charges,Total Costs
0,70 or Older,M,27,Emergency,Home w/ Home Health Services,COVID-19,ISOLATION PROCEDURES,MAJOR RESPIRATORY INFECTIONS AND INFLAMMATIONS,3,Major,Extreme,Medical,Y,"$320,922.43","$60,241.34"
1,70 or Older,M,5,Emergency,Home or Self Care,Urinary tract infections,ADMINISTRATION OF NUTRITIONAL AND ELECTROLYTIC...,KIDNEY AND URINARY TRACT INFECTIONS,3,Major,Major,Medical,Y,"$72,700.17","$12,111.75"
2,50 to 69,F,3,Emergency,Home or Self Care,Paralysis (other than cerebral palsy),LUMBAR PUNCTURE,OTHER DISORDERS OF NERVOUS SYSTEM,2,Moderate,Minor,Medical,Y,"$55,562.51","$8,339.72"
3,50 to 69,M,6,Emergency,Home or Self Care,Complication of other surgical or medical care...,COMPUTERIZED TOMOGRAPHY (CT) WITHOUT CONTRAST,OTHER COMPLICATIONS OF TREATMENT,3,Major,Moderate,Medical,Y,"$109,269.27","$18,443"
4,50 to 69,M,21,Emergency,Left Against Medical Advice,Complication of other surgical or medical care...,LARYNGOSCOPY (DIAGNOSTIC),"POST-OPERATIVE, POST-TRAUMATIC, OTHER DEVICE I...",2,Moderate,Moderate,Medical,Y,"$270,656.16","$48,268.17"

In [3]:
print('Original number of rows:', df.shape[0])

# Define the list of admission types to keep
admission_types_to_keep = ['Elective', 'Emergency', 'Trauma', 'Urgent']

# Filter the DataFrame
df_filtered = df[df['Type of Admission'].isin(admission_types_to_keep)].copy()

print('Number of rows after filtering:', df_filtered.shape[0])
print('First 5 rows of the filtered DataFrame:')
display(df_filtered.head())

Original number of rows: 602176
Number of rows after filtering: 601819
First 5 rows of the filtered DataFrame:

,Age Group,Gender,Length of Stay,Type of Admission,Patient Disposition,CCSR Diagnosis Description,CCSR Procedure Description,APR DRG Description,APR Severity of Illness Code,APR Severity of Illness Description,APR Risk of Mortality,APR Medical Surgical Description,Emergency Department Indicator,Total Charges,Total Costs
0,70 or Older,M,27,Emergency,Home w/ Home Health Services,COVID-19,ISOLATION PROCEDURES,MAJOR RESPIRATORY INFECTIONS AND INFLAMMATIONS,3,Major,Extreme,Medical,Y,"$320,922.43","$60,241.34"
1,70 or Older,M,5,Emergency,Home or Self Care,Urinary tract infections,ADMINISTRATION OF NUTRITIONAL AND ELECTROLYTIC...,KIDNEY AND URINARY TRACT INFECTIONS,3,Major,Major,Medical,Y,"$72,700.17","$12,111.75"
2,50 to 69,F,3,Emergency,Home or Self Care,Paralysis (other than cerebral palsy),LUMBAR PUNCTURE,OTHER DISORDERS OF NERVOUS SYSTEM,2,Moderate,Minor,Medical,Y,"$55,562.51","$8,339.72"
3,50 to 69,M,6,Emergency,Home or Self Care,Complication of other surgical or medical care...,COMPUTERIZED TOMOGRAPHY (CT) WITHOUT CONTRAST,OTHER COMPLICATIONS OF TREATMENT,3,Major,Moderate,Medical,Y,"$109,269.27","$18,443"
4,50 to 69,M,21,Emergency,Left Against Medical Advice,Complication of other surgical or medical care...,LARYNGOSCOPY (DIAGNOSTIC),"POST-OPERATIVE, POST-TRAUMATIC, OTHER DEVICE I...",2,Moderate,Moderate,Medical,Y,"$270,656.16","$48,268.17"